services:
  api-gateway:
    image: api-gateway
    container_name: api-gateway
    build:
      dockerfile: ApiGateway/ApiGateway/Dockerfile
    environment:
      - ConnectionStrings__AuthServiceGrpcEndpoint=$AUTH_SERVICE_GRPC_URL
      - ConnectionStrings__TaskServiceGrpcEndpoint=$TASK_SERVICE_GRPC_URL
      - ConnectionStrings__SolutionServiceGrpcEndpoint=$SOLUTION_SERVICE_GRPC_URL
    ports:
      - "80:80"
    depends_on:
      - auth-service
      - task-service
      - solution-service
      - judge-service
  
  auth-service:
    image: auth-service
    container_name: $AUTH_SERVICE_NAME
    build:
      dockerfile: AuthService/AuthService/Dockerfile
    environment:
      - Kestrel__EndPoints__Grpc__Url=$AUTH_SERVICE_GRPC_ENDPOINT
      - MongoRepository__ConnectionString=$MONGO_DB_URL
    depends_on:
      - mongo
  
  task-service:
    image: task-service
    container_name: $TASK_SERVICE_NAME
    build:
      dockerfile: TaskService/TaskService/Dockerfile
    environment:
      - Kestrel__EndPoints__Grpc__Url=$TASK_SERVICE_GRPC_ENDPOINT
      - MongoRepository__ConnectionString=$MONGO_DB_URL
    depends_on:
      - mongo
  
  judge-service:
    image: judge-service
    container_name: $JUDGE_SERVICE_NAME
    build:
      dockerfile: JudgeService/JudgeService/Dockerfile
    environment:
      - Kestrel__EndPoints__Grpc__Url=$JUDGE_SERVICE_GRPC_URL
      - ConnectionStrings__CppLauncherServiceGrpcEndpoint=$CPP_LAUNCHER_SERVICE_GRPC_URL
      - ConnectionStrings__TestServiceGrpcEndpoint=$TASK_SERVICE_GRPC_URL
    depends_on:
      - cpp-launcher-service

  cpp-launcher-service:
    image: cpp-launcher-service
    container_name: $CPP_LAUNCHER_SERVICE_NAME
    build:
      dockerfile: CppLauncherService/CppLauncherService/Dockerfile
    environment:
      - Kestrel__EndPoints__Grpc__Url=$CPP_LAUNCHER_SERVICE_GRPC_URL
      - Kestrel__EndPoints__Grpc__Protocols=Http2
  
  mongo:
    image: mongo:5.0.15
    container_name: $MONGO_DB_CONTAINER_NAME
  
  mongo-express: # Web interface for managing MongoDB
    image: mongo-express:0.54.0
    container_name: mongo-express
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_BASICAUTH_USERNAME: cyber-dog
      ME_CONFIG_BASICAUTH_PASSWORD: 123
    depends_on:
      - mongo