services:
  # Before launching, make sure you have Let's Encrypt certificates, or run docker-compose.Certbot.yml to obtain them.
  api-gateway:
    volumes:
      - etc-letsencrypt:/etc/letsencrypt/:rw
  
  # When deploying to the target machine, it's necessary to verify and obtain certificates.
  # Test running Certbot using a command in the terminal to check server configuration:
  # docker compose -f docker-compose.yml -f docker-compose.Prod.yml run --rm certbot-test-dry-run
  # Receiving the ssl certificate:
  # docker compose -f docker-compose.yml -f docker-compose.Prod.yml run --rm certbot
  certbot-test-dry-run:
    profiles: [ "certbot-test-dry-run" ]
    command: certonly --standalone -d server.cyber-cat.pro --dry-run
    image: certbot/certbot:latest
    ports:
      - "80:80"
    volumes:
      - etc-letsencrypt:/etc/letsencrypt/:rw
    network_mode: "host"
  
  certbot:
    profiles: [ "certbot" ]
    command: certonly --standalone -d server.cyber-cat.pro --dry-run
    image: certbot/certbot:latest
    ports:
      - "80:80"
    volumes:
      - etc-letsencrypt:/etc/letsencrypt/:rw
    network_mode: "host"

volumes:
  etc-letsencrypt: