services:
  api-gateway:
    extends:
      file: docker-compose.yml
      service: api-gateway
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    volumes:
      - x509stores:/root/.dotnet/corefx/cryptography/x509stores:ro
    depends_on:
      - dev-certs
  
  dev-certs:
    container_name: dev-certs
    build:
      dockerfile: dev-certs.Dockerfile.yml
    volumes:
      - x509stores:/root/.dotnet/corefx/cryptography/x509stores:rw
  
  mongo:
    extends:
      file: docker-compose.Dev.MongoDb.yml
      service: mongo

volumes:
  x509stores: