services:
  judgeservice:
    image: judgeservice
    build:
      context: .
      dockerfile: JudgeService/JudgeService/Dockerfile

  cpplauncherservice:
    image: cpplauncherservice
    build:
      context: .
      dockerfile: CppLauncherService/CppLauncherService/Dockerfile
