services:
  api-gateway:
    image: api-gateway
    container_name: api-gateway
    build:
      context: .
      dockerfile: ApiGateway/ApiGateway/Dockerfile
    environment:
      - ASPNETCORE_URLS=https://+;http://+
      #- Kestrel__EndPoints__Http__Url=$API_GATEWAY_URL
      - ConnectionStrings__AuthServiceGrpcEndpoint=$AUTH_SERVICE_GRPC_URL
      - ConnectionStrings__TaskServiceGrpcEndpoint=$TASK_SERVICE_GRPC_URL
      - ConnectionStrings__SolutionServiceGrpcEndpoint=$SOLUTION_SERVICE_GRPC_URL
      - ConnectionStrings__JudgeServiceGrpcEndpoint=$JUDGE_SERVICE_GRPC_URL
      #- ASPNETCORE_Kestrel__Certificates__Default__Password=secret
      #- ASPNETCORE_Kestrel__Certificates__Default__Path=/https/aspnetapp.pfx
    ports:
      - "443:443"
      - "80:80"
    volumes:
      - etc-letsencrypt:/etc/letsencrypt/:rw
      #- ~/.aspnet/https:/https:ro
    depends_on:
      - auth-service
      - task-service
      - solution-service
  
  auth-service:
    image: auth-service
    container_name: $AUTH_SERVICE_NAME
    build:
      context: .
      dockerfile: AuthService/AuthService/Dockerfile
    environment:
      - ASPNETCORE_URLS=
      - Kestrel__EndPoints__Grpc__Url=$AUTH_SERVICE_GRPC_ENDPOINT
      - Kestrel__EndPoints__Grpc__Protocols=Http2
      - MongoRepository__ConnectionString=$MONGO_DB_URL
      - MongoRepository__DatabaseName=$DATABASE_NAME
    depends_on:
      - mongo
  
  task-service:
    image: task-service
    container_name: $TASK_SERVICE_NAME
    build:
      context: .
      dockerfile: TaskService/TaskService/Dockerfile
    environment:
      - ASPNETCORE_URLS=
      - Kestrel__EndPoints__Grpc__Url=$TASK_SERVICE_GRPC_ENDPOINT
      - Kestrel__EndPoints__Grpc__Protocols=Http2
      - MongoRepository__ConnectionString=$MONGO_DB_URL
      - MongoRepository__DatabaseName=$DATABASE_NAME
    depends_on:
      - mongo
  
  solution-service:
    image: solution-service
    container_name: $SOLUTION_SERVICE_NAME
    build:
      context: .
      dockerfile: SolutionService/SolutionService/Dockerfile
    environment:
      - ASPNETCORE_URLS=
      - Kestrel__EndPoints__Grpc__Url=$SOLUTION_SERVICE_GRPC_URL
      - Kestrel__EndPoints__Grpc__Protocols=Http2
      - MongoRepository__ConnectionString=$MONGO_DB_URL
      - MongoRepository__DatabaseName=$DATABASE_NAME
    depends_on:
      - mongo
  
  judge-service:
    image: judge-service
    container_name: $JUDGE_SERVICE_NAME
    build:
      context: .
      dockerfile: JudgeService/JudgeService/Dockerfile
    environment:
      - ASPNETCORE_URLS=
      - Kestrel__EndPoints__Grpc__Url=$JUDGE_SERVICE_GRPC_URL
      - Kestrel__EndPoints__Grpc__Protocols=Http2
      - ConnectionStrings__CppLauncherServiceGrpcEndpoint=$CPP_LAUNCHER_SERVICE_GRPC_URL
      - ConnectionStrings__TestServiceGrpcEndpoint=$TASK_SERVICE_GRPC_URL
    depends_on:
      - cpp-launcher-service

  cpp-launcher-service:
    image: cpp-launcher-service
    container_name: $CPP_LAUNCHER_SERVICE_NAME
    build:
      context: .
      dockerfile: CppLauncherService/CppLauncherService/Dockerfile
    environment:
      - ASPNETCORE_URLS=
      - Kestrel__EndPoints__Grpc__Url=$CPP_LAUNCHER_SERVICE_GRPC_URL
      - Kestrel__EndPoints__Grpc__Protocols=Http2
  
  mongo:
    image: mongo:5.0.15
    container_name: $MONGO_DB_CONTAINER_NAME
    
  mongo-express: # Веб интерфейс СУБД для управления монгой.
    image: mongo-express:0.54.0
    container_name: mongo-express
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_BASICAUTH_USERNAME: cyber-dog
      ME_CONFIG_BASICAUTH_PASSWORD: 123
    depends_on:
      - mongo

volumes:
  etc-letsencrypt: