version: '3.4'

services:  
  #api-gateway:
   # image: api-gateway
    #container_name: api-gateway
    #build:
      # Для докер файла устаналиваем контекст, какбудто мы запускаем Dockerfile из папки в которой этот файл лежит.
     # context: ./ApiGateway/
      #dockerfile: Dockerfile
    #environment:
     # - ASPNETCORE_URLS=$API_GATEWAY_URL # Переопределяем url и порт на котором будет висеть приложение.
      # - ASPNETCORE_ENVIRONMENT=Development # Чтобы переопределять окуржение и показывать сваггер.
      #- "ConnectionStrings:Database=mongodb://${MONGO_DB_NAME}:27017" # Переопределяем строку подключения к БД, можно ли сделать запись не такой грязной?
    #ports:
     # - "${API_GATEWAY_PORT}:${API_GATEWAY_PORT}"
    #depends_on:
    #  - mongo # Запускаем этот сервис только после того, как запустился контейнер с монгой.

  # Рестарт nginx для перечитки конфигов:
  # docker compose exec nginx nginx -s reload
  nginx:
    container_name: nginx
    build:
      context: ./nginx
      dockerfile: Dockerfile
    ports:
      # Осторожно, nginx смотрит адрес и порт входящего запроса из интернета, а не входящего запроса в контейнер. Поэтому порт должен быть одинаковым по обе стороны.
      - "80:80" # Порт по умолчанию для http запросов.
      - "443:443" # Порт по умолчанию для https запросов.
    depends_on:
     # - api-gateway
      - mongo-express
    volumes:
      # Копируем папку с конфигами для nginx, чтобы конфиги были доступны из контейнера в момент запуска nginx.
      # Настройка файловых хранилищ для взаимодействия нескольких контейнеров.
      # Папки сертификатов, которые нужно читать nginx, чтобы обеспечивать https. ro - только чтение.
      # Слева - локальный путь на хост машине, где расположен сервер (!). Справа - путь, который создастся внутри докер контейнера.
      - www-certbot:/var/www/certbot/:ro
      - etc-letsencrypt:/etc/letsencrypt:ro

  compiler-service:
    image: compiler-service
    build: 
      context: /CompilerServiceAPI/
      dockerfile: Dockerfile
    environment:
      -  ASPNETCORE_URLS=$COMPILER_SERVICE_API_URL
    ports:
      - "${COMPILER_SERVICE_API_PORT}:${COMPILER_SERVICE_API_PORT}"

  mongo:
    image: mongo:5.0.15
    container_name: $MONGO_DB_NAME
    ports:
      - "27017:27017"

  mongo-express: # Веб интерфейс СУБД для управления монгой.
    image: mongo-express:0.54.0
    container_name: mongo-express
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_BASICAUTH_USERNAME: cyber-dog
      ME_CONFIG_BASICAUTH_PASSWORD: 123
    depends_on:
      - mongo

volumes:
  nginx-conf:
  www-certbot:
  etc-letsencrypt: