services:
  # When deploying to the target machine, it's necessary to verify and obtain certificates.
  # Test running Certbot using a command in the terminal to check server configuration:
  # docker compose -f docker-compose.Certbot.yml run --rm certbot certonly --standalone -d server.cyber-cat.pro --dry-run
  # Receiving the ssl certificate:
  # docker compose -f certbot.yml run --rm certbot certonly --standalone -d server.cyber-cat.pro
  certbot:
    image: certbot/certbot:latest
    ports:
      - "80:80"
    volumes:
      # The folder where Certbot will place certificates after verification. rw - read and write permission.
      - etc-letsencrypt:/etc/letsencrypt/:rw
    network_mode: "host"

volumes:
  etc-letsencrypt: